### ISSUE TITLE
Vuetify 0.14: Nuxt + components with "src" caused errors

### ISSUE THREAD

**Issue by Darkside73** [vuetifyjs/vuetify#1009]
### Steps to reproduce
Clone https://github.com/Darkside73/vuetify014-nuxt
Open dev version in browser
Bug affects carousel and card media components and presumably depends on ```src``` attribute

### Versions
Vuetify 0.14
Nuxt 0.10.7

### What is actually happening ?
Error in console and during SSR
```
Nuxt.js Error:

TypeError: _vm._g is not a function
    at Proxy.render (/tmp/vuetify014-nuxt/node_modules/vuetify/dist/vuetify.js:2452:21)
    at VueComponent.Vue._render (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue/dist/vue.runtime.common.js:3605:22)
    at renderComponent (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6698:25)
    at RenderContext.renderNode (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6681:7)
    at RenderContext.next (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:169:14)
    at cachedWrite (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:30:9)
    at renderElement (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6732:5)
    at RenderContext.renderNode (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6685:7)
    at RenderContext.next (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:169:14)
    at RenderContext.cachedWrite [as write] (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:30:9)
    at RenderContext.next (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:172:14)
    at RenderContext.next (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:178:12)
    at RenderContext.cachedWrite [as write] (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:30:9)
    at RenderContext.next (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:172:14)
    at RenderContext.cachedWrite [as write] (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:30:9)
    at RenderContext.next (/tmp/vuetify014-nuxt/node_modules/nuxt/node_modules/vue-server-renderer/build.js:172:14)
```

### Reproduction Link
https://github.com/Darkside73/vuetify014-nuxt

**Comment by Darkside73** [comment]
It's nuxt problem. Version 0.10.7 does not support vue 2.4. It works well with nuxt 1.0
