### ISSUE TITLE
[Bug Report] window is not defined with SSR

### ISSUE THREAD

**Issue by cavinpabua** [vuetifyjs/vuetify#10233]
### Environment
**Vuetify Version:** 1.5.22
**Vue Version:** 2.6.10
**Browsers:** Chrome 79.0.3945.117
**OS:** Linux x86_64

### Steps to reproduce
Used  [UVUE](https://github.com/universal-vue/uvue) to implement SSR in Vue CLI 3. 

Command:
> npm run ssr:build
> npm run ssr:start

### Expected Behavior
No Error on visit

### Actual Behavior

{ 
...
"msg":"window is not defined",
"stack":"ReferenceError: window is not defined
    at Object.56d7 (server-bundle.js:1:635259)
   at o (webpack/bootstrap:36:26)
   at Module.91d2 (uvue.config.js:3:4)
    at o (webpack/bootstrap:36:26)
    at Object.0 (node_modules/vuetify/lib/mixins/transitionable.js:1:0)
    at o (webpack/bootstrap:36:26)
    at server-bundle.js:1:7319
    at Object.<anonymous> (server-bundle.js:1:7328)
    at o (/home/cavin/Desktop/athedian-web/node_modules/vue-server-renderer/build.prod.js:1:77607)
    at /home/cavin/Desktop/athedian-web/node_modules/vue-server-renderer/build.prod.js:1:78200",

"type":"Error",
"v":1
}

### Reproduction Link
<a href="https://codepen.io/cavinpabua/pen/gObdLoP?editors=1010#0" target="_blank">https://codepen.io/cavinpabua/pen/gObdLoP?editors=1010#0</a>

**Comment by KaelWD** [comment]
That is not sufficient to reproduce the issue. Please provide a minimal working git repository or at least a sourcemapped stack trace.

**Comment by johnleider** [comment]
If you have any additional questions, please reach out to us in our [Discord community](https://community.vuetifyjs.com).
