### ISSUE TITLE
[Documentation] vuetifyjs.com website freezes

### ISSUE THREAD

**Issue by nekdolan** [vuetifyjs/vuetify#10800]
### Environment

**Browsers:** Chrome 80.0.3987.132
**OS:** Linux x86_64

### Steps to reproduce
go to vuetifyjs.com
click documentation or ecosystem on the top

### Expected Behavior
page should redirect

### Actual Behavior
page does nothing

### Reproduction Link
<a href="https://vuetifyjs.com" target="_blank">https://vuetifyjs.com</a>

### Other comments
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:40646)
    at p (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:53229)
    at d (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:52920)
    at h (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:53315)
    at T (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:56659)
    at o.__patch__ (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:57017)
    at o.e._update (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:34357)
    at o.r (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:64309)
    at hn.get (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:26620)
    at new hn (https://vuetifyjs.com/vendors~app.754c9d0273ea1f5d22f3.js:1859:26538)

**Comment by KaelWD** [comment]
05c8d3bf7ba06e9099da2b7db198cbaacbefee86

**Comment by jacekkarczmarczyk** [comment]
works fine with https://github.com/vuetifyjs/vuetify/pull/10792
(at least menus and "why vuetify" link work)

**Comment by MajesticPotatoe** [comment]
resolved in 21abed0.
