### ISSUE TITLE
Including scss inside .vue file causes Error at "npm run build"

### ISSUE THREAD

**Issue by smith64fx** [vuetifyjs/vuetify#112]
Hello there,
There is a really strange bug:

I used your SSR Webpack template and I added this to the end of the "GetStartedView.vue" file:

<style src="./view.scss" lang="sass"></style>

I also created the file.

Running "npm run dev" everything works fine.

Running "npm run build" I get this error:

```
ERROR in ./~/sass-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-7e840759!./src/views/view.scss
Module parse failed: /Users/smith/Git/vuetify-ssr/node_modules/sass-loader/index.js!/Users/smith/Git/vuetify-ssr/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-7e840759!/Users/smith/Git/vuetify-ssr/src/views/view.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .test{width:100%}
|
 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/sass-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-7e840759!./src/views/view.scss 4:14-153
 @ ./src/views/GetStartedView.vue
 @ ./src/router/index.js
 @ ./src/app.js
 @ ./src/client-entry.js

ERROR in ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/sass-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-7e840759!./src/views/view.scss
Module build failed: Error
    at /Users/smith/Git/vuetify-ssr/node_modules/webpack/lib/NormalModule.js:210:34
    at /Users/smith/Git/vuetify-ssr/node_modules/webpack/lib/NormalModule.js:164:10
    at /Users/smith/Git/vuetify-ssr/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/Users/smith/Git/vuetify-ssr/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at iterateNormalLoaders (/Users/smith/Git/vuetify-ssr/node_modules/loader-runner/lib/LoaderRunner.js:218:10)
    at /Users/smith/Git/vuetify-ssr/node_modules/loader-runner/lib/LoaderRunner.js:233:3
    at context.callback (/Users/smith/Git/vuetify-ssr/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.onRender [as callback] (/Users/smith/Git/vuetify-ssr/node_modules/sass-loader/index.js:289:9)
    at Object.<anonymous> (/Users/smith/Git/vuetify-ssr/node_modules/async/dist/async.js:2234:31)
    at apply (/Users/smith/Git/vuetify-ssr/node_modules/async/dist/async.js:20:25)
    at Object.<anonymous> (/Users/smith/Git/vuetify-ssr/node_modules/async/dist/async.js:56:12)
    at Object.callback (/Users/smith/Git/vuetify-ssr/node_modules/async/dist/async.js:840:16)
    at options.success (/Users/smith/Git/vuetify-ssr/node_modules/node-sass/lib/index.js:303:32)

ERROR in /Users/smith/Git/vuetify-ssr/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/smith/Git/vuetify-ssr/node_modules/vue-style-loader/index.js!/Users/smith/Git/vuetify-ssr/node_modules/sass-loader/index.js!/Users/smith/Git/vuetify-ssr/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-7e840759!/Users/smith/Git/vuetify-ssr/src/views/view.scss doesn't export content
Child html-webpack-plugin for "index.html":

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

    ERROR in ./~/sass-loader!./~/vue-loader/lib/style-rewriter.js?id=data-v-7e840759!./src/views/view.scss
    Module parse failed: /Users/smith/Git/vuetify-ssr/node_modules/sass-loader/index.js!/Users/smith/Git/vuetify-ssr/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-7e840759!/Users/smith/Git/vuetify-ssr/src/views/view.scss Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    | .test{width:100%}
    |
Child extract-text-webpack-plugin:
```

Any ideas why I get this error?

**Comment by johnleider** [comment]
Go ahead and either update the client.config or re-init the vue template.
