### ISSUE TITLE
[Bug Report] Vue 3.0 (vue-next) npm run serve error - No matching rule for vue-loader found

### ISSUE THREAD

**Issue by alexsorinsky** [vuetifyjs/vuetify#11346]
### Environment
**Vuetify Version:** 2.2.27
**Vue Version:** 3.0.0-beta.10
**Browsers:** Firefox 76.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. vue create t3v
2. vue add vue-next
3. vue add vuetify
4. npm run serve

### Expected Behavior
should work

### Actual Behavior
```
 ~/shm/t3m   master ●  npm run serve

> t3m@0.1.0 serve /dev/shm/t3m
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/dev/shm/t3m/node_modules/vuetify-loader/lib/plugin.js:29:13)
    at webpack (/dev/shm/t3m/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/dev/shm/t3m/node_modules/@vue/cli-service/lib/commands/serve.js:162:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! t3m@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the t3m@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by MajesticPotatoe** [comment]
Vuetify 2.x will not work with Vue 3 due to internal changes with Vue 3. You will need to wait for Vuetify 3.x to be able to use Vuetify w/ Vue 3.

You can follow v3 development on our [Notion Board](https://www.notion.so/Vuetify-Next-edf8fdb074eb4643a7196aaf8e5d5cad)
