### ISSUE TITLE
[Bug Report] v-icon TypeError: Cannot read property 'icons' of undefined

### ISSUE THREAD

**Issue by nanpx** [vuetifyjs/vuetify#13163]
### Environment
**Vuetify Version:** 2.4.5
**Last working version:** 2.3.23
**Vue Version:** 2.6.11
**Browsers:** Chrome 88.0.4324.182
**OS:** Mac OS 10.15.7

### Steps to reproduce
```bash
git clone https://github.com/nanpx/v-icon-bug-demo.git
cd v-icon-bug-demo
npm install
npm run test:unit

TypeError: Cannot read property 'icons' of undefined
      at remapInternalIcon (node_modules/vuetify/dist/webpack:/Vuetify/src/util/helpers.ts:225:33)
      at VueComponent.getIcon (node_modules/vuetify/dist/webpack:/Vuetify/src/components/VIcon/VIcon.ts:72:31)
      at Proxy.render (node_modules/vuetify/dist/webpack:/Vuetify/src/components/VIcon/VIcon.ts:217:23)
      at VueComponent.Vue._render (node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:21)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6033:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5934:9)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6033:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5934:9)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
      at createChildren (node_modules/vue/dist/vue.runtime.common.dev.js:6033:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5934:9)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at init (node_modules/vue/dist/vue.runtime.common.dev.js:3112:13)
      at createComponent (node_modules/vue/dist/vue.runtime.common.dev.js:5958:9)
      at createElm (node_modules/vue/dist/vue.runtime.common.dev.js:5905:9)
      at VueComponent.patch [as __patch__] (node_modules/vue/dist/vue.runtime.common.dev.js:6455:7)
      at VueComponent.Vue._update (node_modules/vue/dist/vue.runtime.common.dev.js:3933:19)
      at VueComponent.updateComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4054:10)
      at Watcher.get (node_modules/vue/dist/vue.runtime.common.dev.js:4465:25)
      at new Watcher (node_modules/vue/dist/vue.runtime.common.dev.js:4454:12)
      at mountComponent (node_modules/vue/dist/vue.runtime.common.dev.js:4061:3)
      at VueComponent.Object.<anonymous>.Vue.$mount (node_modules/vue/dist/vue.runtime.common.dev.js:8392:10)
      at mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:13977:21)
      at Object.<anonymous> (tests/unit/HelloWorld.spec.js:16:21)
```

### Expected Behavior
Regardless of using `mount` or `shallowMount` from @vue/test-utils, I'd expect the same simple test to pass.

### Actual Behavior
`mount` fails with the provided error, but `shallowMount` passes.

### Reproduction Link
<a href="https://github.com/nanpx/v-icon-bug-demo" target="_blank">https://github.com/nanpx/v-icon-bug-demo</a>

### Other comments
Possibly related to https://github.com/vuetifyjs/vuetify/issues/12962 and caused by https://github.com/vuetifyjs/vuetify/commit/41fd082dc2ae59a35b399e5d86cf4d66729ec63b

**Comment by KaelWD** [comment]
`localVue.use(Vuetify)` will not work: https://vuetifyjs.com/en/getting-started/unit-testing/#bootstrapping-vuetify

**Comment by nanpx** [comment]
@KaelWD thank you. Has that always been the case or did that change within the last year? I just need a sanity check because I thought we followed documentation setting up our tests with Vuetify.

**Comment by KaelWD** [comment]
It's been the case since 2.0 when we started using `Vue.extend()`. Most of the time it's fine but anything that depends on `this.$vuetify` will not work. v-icon didn't use `$vuetify` until v2.4 which is why it's only just become an issue for you.
