### ISSUE TITLE
[Bug Report][2.5.5] Vuetify and Jest are not working with TSX

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vuetifyjs/vuetify#13841]
### Environment
**Vuetify Version:** 2.5.5
**Vue Version:** 2.6.12
**Browsers:** Chrome 91.0.4472.114
**OS:** Windows 10

### Steps to reproduce
1. yarn (install deps)
2. yarn test (tests should fail)

Uncomment `transformIgnorePatterns: ["node_modules/(?!(vuetify)/)"],` line in `jest.config.js` to make tests pass.

### Expected Behavior
Tests are passing without `transformIgnorePatterns: ["node_modules/(?!(vuetify)/)"],`

### Actual Behavior
Tests are failing without `transformIgnorePatterns: ["node_modules/(?!(vuetify)/)"],`

### Reproduction Link
<a href="https://github.com/Maxim-Mazurok/vue-jest-tsx-error-repro/tree/vuetify" target="_blank">https://github.com/Maxim-Mazurok/vue-jest-tsx-error-repro/tree/vuetify</a>

### Other comments
See also: https://github.com/wonderful-panda/vue-tsx-support/issues/78 which was fixed.

**Comment by KaelWD** [comment]
You still have vue-tsx-support@^3.1.0

**Comment by Maxim-Mazurok** [comment]
> You still have vue-tsx-support@3.1.0 installed

No, please see Reproduction Link: https://github.com/Maxim-Mazurok/vue-jest-tsx-error-repro/tree/vuetify

Note, that I'm linking to the vuetify branch, not mater branch. Cheers!

**Comment by KaelWD** [comment]
> Tests are failing without `transformIgnorePatterns`

OK yes that is expected, Vuetify distributes es modules so they must be transpiled to work with jest.

**Comment by Maxim-Mazurok** [comment]
> Vuetify distributes es modules so they must be transpiled to work with jest

So, how about distributing both CommonJS and ES module build of vuetify? Multiple entry points can be exposed with both esmodule and commonjs. See @toomuchdesign comments https://github.com/wonderful-panda/vue-tsx-support/issues/78#issuecomment-832213222, that's how @wonderful-panda solved this for `vue-tsx-support`.

Would be great to solve this for vuetify as well. So far it's the only library in our project that we have to transpile, which consumes quite a lot of time for tests startup since it's so large.

**Comment by KaelWD** [comment]
You may be able to use an alias from `/lib` to `/es5` for tests.

**Comment by Maxim-Mazurok** [comment]
> You may be able to use an alias from `/lib` to `/es5` for tests.

I'm getting this error when using `/es5`
```
    src/components/HelloWorld.tsx:2:22 - error TS7016: Could not find a declaration file for module 'vuetify/es5'. '/home/maxim/vue-jest-tsx-error-repro/node_modules/vuetify/es5/index.js' implicitly has an 'any' type.
      Try `npm i --save-dev @types/vuetify` if it exists or add a new declaration (.d.ts) file containing `declare module 'vuetify/es5';`

    2 import { VApp } from "vuetify/es5";
                           ~~~~~~~~~~~~~
```

See https://github.com/Maxim-Mazurok/vue-jest-tsx-error-repro/commit/034e339f20eecffc0434ad4389d21553e2a86336 in [vuetify-es5](https://github.com/Maxim-Mazurok/vue-jest-tsx-error-repro/tree/) branch

Looks like it can't find type definitions for vuetify...

**Comment by KaelWD** [comment]
Yeah you still use `/lib` in the code, with `moduleNameMapper: { '^vuetify/lib/(.*)': 'vuetify/es5/$1', }`

**Comment by Maxim-Mazurok** [comment]
> Yeah you still use `/lib` in the code, with `moduleNameMapper: { '^vuetify/lib(.*)': 'vuetify/es5$1' }`

Thanks, I changed it to `^vuetify/lib(/?.*)` to make it work with `vuetify/lib`, not only `vuetify/lib/*`.

However, now I'm getting this error:
```
yarn run v1.22.10
$ vue-cli-service test:unit
ts-jest[versions] (WARN) Version 4.3.4 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  tests/unit/example.spec.ts
  ● Test suite failed to run

    /home/maxim/vue-jest-tsx-error-repro/node_modules/vuetify/src/components/VApp/VApp.sass:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@import '../../styles/styles.sass'
                                                                                             ^

    SyntaxError: Invalid or unexpected token

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.728s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Which is related to sass not being transpired, as far as I understand?.. How would you recommend to fix this?

**Comment by Maxim-Mazurok** [comment]
I've tried [identity-obj-proxy](https://www.npmjs.com/package/identity-obj-proxy) in [vuetify-es5-identity-obj-proxy branch](https://github.com/Maxim-Mazurok/vue-jest-tsx-error-repro/tree/vuetify-es5-identity-obj-proxy).

It runs tests, but fails to render correctly:
```
yarn run v1.22.10
$ vue-cli-service test:unit
ts-jest[versions] (WARN) Version 4.3.4 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  tests/unit/example.spec.ts
  HelloWorld
    ✕ renders props.msg when passed (8ms)

  ● HelloWorld › renders props.msg when passed

    expect(received).toMatch(expected)

    Expected substring: "new message"
    Received string:    ""

       8 |       propsData: { msg },
       9 |     });
    > 10 |     expect(wrapper.text()).toMatch(msg);
         |                            ^
      11 |   });
      12 | });
      13 |

      at Object.<anonymous> (tests/unit/example.spec.ts:10:28)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.019s, estimated 2s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Maxim-Mazurok** [comment]
Tried `@testing-library/vue` in [vuetify-es5-@testing-library/vue branch](https://github.com/Maxim-Mazurok/vue-jest-tsx-error-repro/tree/vuetify-es5-%40testing-library/vue). No luck, Vuetify component doesn't render:

```
yarn run v1.22.10
$ vue-cli-service test:unit
ts-jest[versions] (WARN) Version 4.3.4 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  tests/unit/example.spec.tsx
  ✕ renders app name (27ms)

  ● renders app name

    expect(received).not.toThrow()

    Error name:    "TestingLibraryElementError"
    Error message: "Unable to find an element with the text: new message. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.·
    <body>
      <div>
        <!---->
      </div>
    </body>"

          16 |   );
          17 |
        > 18 |   expect(() => getByText(msg)).not.toThrow();
             |                ^
          19 | });
          20 |

          at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
          at tests/unit/example.spec.tsx:18:16
          at Object.<anonymous> (tests/unit/example.spec.tsx:18:36)

      16 |   );
      17 |
    > 18 |   expect(() => getByText(msg)).not.toThrow();
         |                                    ^
      19 | });
      20 |

      at Object.<anonymous> (tests/unit/example.spec.tsx:18:36)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.426s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by KaelWD** [comment]
Ok that's my bad looks like `/es5` uses the same entry as the UMD build which doesn't re-export components. It takes two maps to fix this:
```js
  moduleNameMapper: {
    '^vuetify/lib': 'vuetify/es5/entry-lib',
    '^vuetify/lib/(.*)': 'vuetify/es5/$1',
  }
```

**Comment by Maxim-Mazurok** [comment]
That fixes the issue in the original repro, thanks!
However, it didn't work when I was import `VThemeProvider from "vuetify/lib/components/VThemeProvider"`, see [vuetify-es5-identity-obj-proxy-VThemeProvider](https://github.com/Maxim-Mazurok/vue-jest-tsx-error-repro/tree/vuetify-es5-identity-obj-proxy-VThemeProvider) branch.

Here's the error:
```
yarn run v1.22.10
$ vue-cli-service test:unit
ts-jest[versions] (WARN) Version 4.3.4 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=2.7.0 <4.0.0). Please do not report issues in ts-jest if you are using unsupported versions.
 FAIL  tests/unit/example.spec.ts
  HelloWorld
    ✕ renders props.msg when passed (13ms)

  ● HelloWorld › renders props.msg when passed

    TypeError: Cannot call a class as a function

      12 |   },
      13 |   render(): VNode {
    > 14 |     return (
         |     ^
      15 |       <VThemeProvider>
      16 |         <h1>{this.msg}</h1>
      17 |       </VThemeProvider>

      at _classCallCheck (node_modules/vuetify/es5/framework.js:14:99)
      at Proxy.render (src/components/HelloWorld.tsx:14:5)
      at Object.<anonymous> (tests/unit/example.spec.ts:7:21)

  console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
    [Vue warn]: Error in render: "TypeError: Cannot call a class as a function"
    
    found in
    
    ---> <HelloWorld>
           <Root>

  console.error node_modules/vue/dist/vue.runtime.common.dev.js:1893
    TypeError: Cannot call a class as a function
        at _classCallCheck (/home/maxim/vue-jest-tsx-error-repro/node_modules/vuetify/es5/framework.js:14:99)
        at Vuetify (/home/maxim/vue-jest-tsx-error-repro/node_modules/vuetify/src/framework.ts:38:50)
        at resolveAsyncComponent (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:3697:15)
        at createComponent (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:3213:12)
        at _createElement (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:3448:13)
        at createElement (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:3368:10)
        at vm.$createElement (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:3508:54)
        at createElement (/home/maxim/vue-jest-tsx-error-repro/node_modules/@vue/test-utils/dist/vue-test-utils.js:2543:36)
        at Proxy.render (/home/maxim/vue-jest-tsx-error-repro/src/components/HelloWorld.tsx:14:5)
        at VueComponent.Vue._render (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:3559:22)
        at VueComponent.updateComponent (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:4069:21)
        at Watcher.get (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:4481:25)
        at new Watcher (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:4470:12)
        at mountComponent (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:4076:3)
        at VueComponent.Object.<anonymous>.Vue.$mount (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:8436:10)
        at init (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:3131:13)
        at createComponent (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:6002:9)
        at createElm (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:5949:9)
        at VueComponent.patch [as __patch__] (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:6499:7)
        at VueComponent.Vue._update (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:3948:19)
        at VueComponent.updateComponent (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:4069:10)
        at Watcher.get (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:4481:25)
        at new Watcher (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:4470:12)
        at mountComponent (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:4076:3)
        at VueComponent.Object.<anonymous>.Vue.$mount (/home/maxim/vue-jest-tsx-error-repro/node_modules/vue/dist/vue.runtime.common.dev.js:8436:10)
        at mount (/home/maxim/vue-jest-tsx-error-repro/node_modules/@vue/test-utils/dist/vue-test-utils.js:14066:21)
        at shallowMount (/home/maxim/vue-jest-tsx-error-repro/node_modules/@vue/test-utils/dist/vue-test-utils.js:14092:10)
        at Object.<anonymous> (/home/maxim/vue-jest-tsx-error-repro/tests/unit/example.spec.ts:7:21)
        at Object.asyncJestTest (/home/maxim/vue-jest-tsx-error-repro/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
        at /home/maxim/vue-jest-tsx-error-repro/node_modules/jest-jasmine2/build/queueRunner.js:43:12
        at new Promise (<anonymous>)
        at mapper (/home/maxim/vue-jest-tsx-error-repro/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at /home/maxim/vue-jest-tsx-error-repro/node_modules/jest-jasmine2/build/queueRunner.js:73:41

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.031s, estimated 2s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've been using this import style only for this component because it was left out, but this issue was fixed: https://github.com/vuetifyjs/vuetify/issues/13578

So, now my project works great with Vuetify + TSX + Jest! Thank you so much for your help! 🤗

**Comment by KaelWD** [comment]
```diff
- '^vuetify/lib': 'vuetify/es5/entry-lib',
+ '^vuetify/lib$': 'vuetify/es5/entry-lib',
```

**Comment by Maxim-Mazurok** [comment]
Awesome, now it works even with `VThemeProvider from "vuetify/lib/components/VThemeProvider"` style! Cheers!

**Comment by Maxim-Mazurok** [comment]
All the way from 41.504s to 9.92s to run all our unit tests with jest cache cleared, brilliant! 💎

**Comment by KaelWD** [comment]
Interesting that it was so slow, do you have a lot of tests? The test suite in this repo only takes 17 seconds to run 1609 tests with a clear cache and transpiling from source. With a hot cache it takes just 13s.

**Comment by Maxim-Mazurok** [comment]
On my PC (WSL2 on WIN10, Ryzen 3600) it was 18s (no cache) and 14s (cache) for vuetify package.

We only have 39 tests so far.

Perhaps, it has something to do with the fact that we're using `@testing-library/vue` instead of `@vue/test-utils`.
To render a simple component 1000 times, testing-library approach took me 6s, while test-utils took 5s. Both with no cache.

But I think the real reason is that we test some components without proper abstraction. For example, rendering a simple component 1000 times took only 6s, but rendering the App component (that contains all parts of our app) 1000 times takes well over a minute.

Also, our production build takes a bit over a minute usually.

**Comment by stephane303** [comment]
Followed this thread, updated everything, but was unabled to get rid of the error (unless I use` transformIgnorePatterns: ["node_modules/(?!(vuetify)/)"]`).
Can you recap the steps to resolve the issue, thank you.

**Comment by Maxim-Mazurok** [comment]
```js
/* eslint-disable @typescript-eslint/no-var-requires */
const deepmerge = require("deepmerge");
const defaultTsBabelPreset = require("@vue/cli-plugin-unit-jest/presets/typescript-and-babel/jest-preset");

module.exports = {
  ...deepmerge(defaultTsBabelPreset, {
    globals: {
      "ts-jest": {
        tsConfig: "<rootDir>/jest/tsconfig.json", // for old jest (deprecated)
        tsconfig: "<rootDir>/jest/tsconfig.json", // for new jest
        diagnostics: {
          pathRegex: "jest/.*.spec.tsx?$", // current ts-jest, deprecated
          exclude: ["**/jest/**/*.spec.ts?(x)"], // ts-jest 27+
        },
      },
    },
    roots: ["<rootDir>/jest/"], // to resolve __mocks__ dir correctly
  }),
  ...{
    moduleNameMapper: {
      "^vuetify/lib$": "vuetify/es5/entry-lib",
      "^vuetify/lib/(.*)": "vuetify/es5/$1",
      "\\.(css|less|scss|sass)$": "identity-obj-proxy",
    },
    setupFiles: ["./jest/setup.ts"],
    setupFilesAfterEnv: ["./jest/setupAfterEnv.ts"],
    testMatch: ["**/jest/**/*.spec.ts?(x)"],
    clearMocks: true,
    transformIgnorePatterns: ["<rootDir>/node_modules/(?!vee-validate/dist/rules)"],
  },
};
```

**Comment by stephane303** [comment]
Thank you, but I have another issue now, I will just use ` ["node_modules/(?!(vuetify)/)"]`, I don't see the downside of doing this.
