### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] Undefined function 'xs': math.div($grid-gutter, 12)

### ISSUE THREAD

**Issue by Loremaster** [vuetifyjs/vuetify#14199]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.19
**Browsers:** Chrome 93.0.4577.82
**OS:** Mac OS 10.15.7

### Steps to reproduce
Trying to setup project with vite and vuetify 3 based on [example](https://github.com/peshanghiwa/Vue3-Vite-Vuetify3-Typescript-Template). I added some fixes locally but still struggle to make it work. 

Steps:
1. Clone repo: `$ git clone git@github.com:Loremaster/Vue3-Vite-Vuetify3-Typescript-Template.git`
2. Install dependencies: `$ yarn`
3. Run dev server: `$ yarn dev`

### Expected Behavior
I expect to see the page with content

### Actual Behavior
I receive this error:

```
5:13:04 PM [vite] Internal server error: Undefined function.
    ╷
115 │     'xs': math.div($grid-gutter, 12),
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/vuetify/lib/styles/settings/_variables.scss 115:11  @forward
  node_modules/vuetify/lib/styles/settings/_index.sass 1:1         @forward
  node_modules/vuetify/lib/styles/main.sass 3:1                    root stylesheet
  Plugin: vite:css
  File: /Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/vuetify/lib/styles/settings/_variables.scss
  Error: Undefined function.
      ╷
  115 │     'xs': math.div($grid-gutter, 12),
      │           ^^^^^^^^^^^^^^^^^^^^^^^^^^
      ╵
    node_modules/vuetify/lib/styles/settings/_variables.scss 115:11  @forward
    node_modules/vuetify/lib/styles/settings/_index.sass 1:1         @forward
    node_modules/vuetify/lib/styles/main.sass 3:1                    root stylesheet
      at Object._newRenderError (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:13174:19)
      at Object._wrapException (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:13000:16)
      at _render_closure1.call$2 (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:81147:21)
      at _RootZone.runBinary$3$3 (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:27268:18)
      at _FutureListener.handleError$1 (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:25818:19)
      at _Future__propagateToListeners_handleError.call$0 (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:26116:49)
      at Object._Future__propagateToListeners (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:4539:77)
      at _Future._completeError$2 (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:25948:9)
      at _AsyncAwaitCompleter.completeError$2 (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:25602:12)
      at Object._asyncRethrow (/Users/serj/Projects/Vue3-Vite-Vuetify3-Typescript-Template/node_modules/sass/sass.dart.js:4338:17)
```

### Reproduction Link
<a href="https://github.com/Loremaster/Vue3-Vite-Vuetify3-Typescript-Template" target="_blank">https://github.com/Loremaster/Vue3-Vite-Vuetify3-Typescript-Template</a>

**Comment by KaelWD** [comment]
Vuetify 3 uses sass > v1.33
