### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] Migrating from 3.0.0-alpha.10 => 3.0.0-alpha.11 causes `vite` to fail

### ISSUE THREAD

**Issue by tecfu** [vuetifyjs/vuetify#14214]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Last working version:** 3.0.0-alpha.10
**Vue Version:** 3.2.6
**Browsers:** Chrome 93.0.4577.82
**OS:** Linux x86_64

### Steps to reproduce
```bash
npm install
npm run dev
```

### Expected Behavior
Vit dev server should run. 

### Actual Behavior
Error Message:

```
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  vuetify/lib/components (imported by myproject/src/plugins/vuetify.ts)
  vuetify/lib/directives (imported by myproject/src/plugins/vuetify.ts)

Are they installed?
    at optimizeDeps (myproject/node_modules/vite/dist/node/chunks/dep-972722fa.js:73454:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOptimize (myproject/node_modules/vite/dist/node/chunks/dep-972722fa.js:74167:48)
    at async Server.httpServer.listen (myproject/node_modules/vite/dist/node/chunks/dep-972722fa.js:74183:21)
```

### Reproduction Link
<a href="https://github.com/tecfu/Vue3-Vite-Vuetify3-Typescript-Template" target="_blank">https://github.com/tecfu/Vue3-Vite-Vuetify3-Typescript-Template</a>

### Other comments
I forked a vue3-vite-vuetify boilerplate repository to demo this issue. 

Vite will run on Vuetify 3.0.0-alpha.10 *so long as* after downgrading from 3.0.0-alpha.11 you have run:
```
git checkout package-lock.json
```

**Comment by tecfu** [comment]
The is plugins/vuetify.ts is as follows: https://github.com/tecfu/Vue3-Vite-Vuetify3-Typescript-Template/blob/master/src/plugins/vuetify.ts

```js
import '@mdi/font/css/materialdesignicons.css'
import 'vuetify/lib/styles/main.sass'
import { createVuetify } from 'vuetify'
import * as components from 'vuetify/lib/components'
import * as directives from 'vuetify/lib/directives'


export const vuetify = createVuetify({
  components,
  directives,
  theme: {
    themes: {
      light: {
        colors: {
          primary: '#41b883',
          background: '#35495e',
          error: '#d63031',
          info: '#0984e3',
          secondary: '#fdcb6e',
          success: '#00cec9',
          surface: '#6c5ce7',
          warning: '#2d3436',
        },
        dark: false,
        variables: {},
      },
    },
  },
})
```

**Comment by KaelWD** [comment]
Read the release notes
