### ISSUE TITLE
[Bug Report][3.0.0-alpha.11] vue-cli-service serve could not start the app after add vuetify 3.0.0-alpha.11

### ISSUE THREAD

**Issue by kangchengkun** [vuetifyjs/vuetify#14248]
### Environment
**Vuetify Version:** 3.0.0-alpha.11
**Vue Version:** 3.2.20
**Browsers:** Chrome 94.0.4606.81
**OS:** Mac OS 10.15.7

### Steps to reproduce
Follow this docu: https://next.vuetifyjs.com/en/getting-started/installation/

1. Install latest Vue Cli: @vue/cli 4.5.13
2. Choose: Manually select features
```
? Please pick a preset: Manually select features
? Check the features needed for your project: 
 ◉ Choose Vue version
 ◉ Babel
 ◯ TypeScript
 ◯ Progressive Web App (PWA) Support
 ◉ Router
 ◉ Vuex
 ◯ CSS Pre-processors
 ◉ Linter / Formatter
 ◉ Unit Testing
❯◉ E2E Testing

```
and choose Vue 3.x

3. cd my-app
4. vue add vuetify
5. Choose: Vuetify 3 Preview (Vuetify 3)
6. main.js
```
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import vuetify from './plugins/vuetify';
import { loadFonts } from './plugins/webfontloader';

loadFonts();

createApp(App).use(router).use(store).use(vuetify).mount('#app');

```
7. vuetify.js
```
// Styles
import '@mdi/font/css/materialdesignicons.css';
import 'vuetify/styles';

// Vuetify
import { createVuetify } from 'vuetify';

export default createVuetify();
// https://vuetifyjs.com/en/introduction/why-vuetify/#feature-guides

```
8. Run `vue-cli-service serve`

### Expected Behavior
App can start properly

### Actual Behavior

App failed to start with below error:

```
 ERROR  SyntaxError: Unexpected token '.'
/Users/xxxxxxxx/go/src/vuetify-vue3/node_modules/vuetify-loader/dist/scriptLoader.js:7
    const render = /^import { render } from "(.+)"$/m.exec(content)?.[1];
                                                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/e0445226/go/src/vuetify-vue3/node_modules/vuetify-loader/dist/index.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
error Command failed with exit code 1.
```

### Reproduction Link
<a href="https://github.com/kangchengkun/vuetify-vue3" target="_blank">https://github.com/kangchengkun/vuetify-vue3</a>

**Comment by planeiii-te** [comment]
@KaelWD Duplicate of which issue?
