### ISSUE TITLE
[Bug Report][2.5.9] VRipple - TypeError: Cannot read properties of undefined (reading 'clientX')

### ISSUE THREAD

**Issue by michalzaq12** [vuetifyjs/vuetify#14774]
### Environment
**Vuetify Version:** 2.5.9
**Vue Version:** 2.6.14
**Browsers:** Other
**OS:** Android

### Steps to reproduce
Unable to reproduce myself. This is an error from a user's device (Samsung Internet v16.0) that was captured by Sentry error tracking.

### Expected Behavior
No errors

### Actual Behavior
TypeError: Cannot read properties of undefined (reading 'clientX')
 https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/directives/ripple/index.ts#L46
```
TypeError: Cannot read properties of undefined (reading 'clientX')
  at calculate(../../../src/directives/ripple/index.ts:52:14)
  at ripples(../../../src/directives/ripple/index.ts:96:55)
  at Object.element._ripple.showTimerCommit(../../../src/directives/ripple/index.ts:190:7)
  at HTMLButtonElement.y(../../../src/directives/ripple/index.ts:212:5)
```

### Reproduction Link
<a href="https://codepen.io/michalzaq12/pen/bGYQeym" target="_blank">https://codepen.io/michalzaq12/pen/bGYQeym</a>

**Comment by michalzaq12** [comment]
Also visible in a browser other than Samsung Internet v16.0

**Browser**
Name | Chrome Mobile
-- | --
Version | 98.0.4758

**Device**
Brand | Samsung
-- | --
Family | Samsung SM-G998U
Model | SM-G998U

**OS**
Name | Android
-- | --
Version | 12

**Comment by lioneaglesolutions** [comment]
### Missing Reproduction

You've submitted an issue that does not contain a **valid** or **simple** reproduction. In order to effectively disposition this, we need to verify that the problem exists **outside** of your environment concisely as possible. This issue will be tagged as `needs reproduction` for the next 48 hours before being closed.

You can find information on how to contribute to Vuetify below:

- [[Vuetify Contributing Guide](https://vuetifyjs.com/getting-started/contributing/)](https://vuetifyjs.com/getting-started/contributing/)
- [[Contributing Rules](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)](https://github.com/vuetifyjs/vuetify/blob/master/.github/CONTRIBUTING.md)
- [[Codepen](https://template.vuetifyjs.com/)](https://template.vuetifyjs.com/)
- [[Codepen w/Router](https://codepen.io/zikeji/pen/ypeQNm)](https://codepen.io/zikeji/pen/ypeQNm)
- A **simple** and **small** repository

Keep in mind we cannot debug a personal application. Thank you for your understanding. If you have any additional questions, please reach out to us in our [[Discord community](https://community.vuetifyjs.com/)](https://community.vuetifyjs.com/).

**Comment by KaelWD** [comment]
Closing due to inactivity
