### ISSUE TITLE
[Bug Report][3.0.0-beta.5] Can't build vite-plugin-ssr project with Vuetify variable overrides 

### ISSUE THREAD

**Issue by DenisLug** [vuetifyjs/vuetify#15510]
### Environment
**Vuetify Version:** 3.0.0-beta.5
**Vue Version:** 3.2.3
**Browsers:** Chrome 103.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
git clone https://github.com/DenisLug/vite-plugin-ssr-vuetify.git
cd vite-plugin-ssr-vuetify
npm install
npm run build

### Expected Behavior
Project should build without any errors.

### Actual Behavior
The following error is thrown:
```
Error: Cannot find module 'vuetify/lib/components' from '/home/brillout/tmp/vuetify3-ssr/pages/_default'
    at Function.resolveSync [as sync] (/home/brillout/tmp/vuetify3-ssr/node_modules/resolve/lib/sync.js:107:15)
    at resolveFrom$3 (/home/brillout/tmp/vuetify3-ssr/node_modules/vite/dist/node/chunks/dep-11db14da.js:4076:29)
    at resolve (/home/brillout/tmp/vuetify3-ssr/node_modules/vite/dist/node/chunks/dep-11db14da.js:73358:22)
    at nodeRequire (/home/brillout/tmp/vuetify3-ssr/node_modules/vite/dist/node/chunks/dep-11db14da.js:73337:25)
    at ssrImport (/home/brillout/tmp/vuetify3-ssr/node_modules/vite/dist/node/chunks/dep-11db14da.js:73290:20)
    at eval (/pages/_default/vuetify.js:9:31)
    at instantiateModule (/home/brillout/tmp/vuetify3-ssr/node_modules/vite/dist/node/chunks/dep-11db14da.js:73323:166)
```

### Reproduction Link
<a href="https://github.com/DenisLug/vite-plugin-ssr-vuetify" target="_blank">https://github.com/DenisLug/vite-plugin-ssr-vuetify</a>

**Comment by KaelWD** [comment]
- The correct import is `import * as components from 'vuetify/components'`
- You have `autoImport` enabled so you don't need the global components and directives imports anyway

**Comment by brillout** [comment]
I do think it's a Vuetify problem though; https://github.com/brillout/vite-plugin-ssr/issues/379#issuecomment-1195456104. Note that vite-plugin-ssr has quite an extensive test suite integrating all kinds of tools, so the problem is most likely on Vuetify's side.

@KaelWD Minimal reproduction: https://github.com/DenisLug/vite-plugin-ssr-0.4-vuetify.

> * The correct import is `import * as components from 'vuetify/components'`
> * You have `autoImport` enabled so you don't need the global components and directives imports anyway

@DenisLug Did you try this?

**Comment by DenisLug** [comment]
Yes, the autoImport is set to true in the [vite-plugin-ssr-0.4-vuetify](https://github.com/DenisLug/vite-plugin-ssr-0.4-vuetify) project but the build still fails.

**Comment by DenisLug** [comment]
@KaelWD Could you please take a look at this?
