### ISSUE TITLE
[Bug Report][3.0.0] VFileInput - Calling .reset() produces a TypeError due to accessing a property on null

### ISSUE THREAD

**Issue by mhio** [vuetifyjs/vuetify#16053]
### Environment
**Vuetify Version:** 3.0.0
**Vue Version:** 3.2.42
**Browsers:** Chrome 106.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
- Click the VFileInput and select a file
- Click "Reset File" calling .reset() on the VFileInput

### Expected Behavior
VFileInput resets to blank. 

### Actual Behavior
VFileInput produces TypeError
```
TypeError: Cannot read properties of null (reading 'length')
    at default (VFileInput.tsx:206:39)
    at runtime-dom.esm-browser.js:5674:35
    at Proxy.renderFnWithContext (runtime-dom.esm-browser.js:2357:19)
    at Proxy.<anonymous> (VField.tsx:276:15)
    at renderComponentRoot (runtime-dom.esm-browser.js:2403:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-dom.esm-browser.js:7118:34)
    at ReactiveEffect.run (runtime-dom.esm-browser.js:537:25)
    at instance.update (runtime-dom.esm-browser.js:7161:56)
    at updateComponent (runtime-dom.esm-browser.js:6986:26)
    at processComponent (runtime-dom.esm-browser.js:6919:13)
```

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNpdUMFuwjAM/RUvmlSQIEVsJ1TQdpm2L9iBcOhad0RLk6hxERLqv88J0MGkSPGzn/2evT2JV+/loUexEkWoOu0JAlLvN8rq1ruO4AQdNjBA07kWMqZmyipbORsI2vAN61ifZO9ojINP15n6IZteCY02GC6U7Y7TRX5W4fkMxhiPSavGpuwNayoL0CLtXR1WZwQ8g5298cAP63uaTC/pWKC+s0B7HeQjKwUZZRNLpqYJC0fiMIv/oCy/eyOErTclISOA4jAvfbxA7GHQltpeUMKER5o3Gk0NXHQ1mrUSfAolIL/lRRdzHW3E/Zkz2mLmX2e60f/eL7LwUhld/TDjfnMlNilR5Il29cloNBrBeYUiv1lNDDPxJJfyeSlisJALsfsFBPGqBQ==)

### Other comments

Calling [`.reset()`](https://github.com/vuetifyjs/vuetify/blob/0a562f087658c1e533a4f431b70031daa4bcde01/packages/vuetify/src/composables/validation.ts#L144-L147) results in VFieldInput accessing [`.value` on `null`](https://github.com/vuetifyjs/vuetify/blob/0a562f087658c1e533a4f431b70031daa4bcde01/packages/vuetify/src/components/VFileInput/VFileInput.tsx#L206)

Might just need `model.value?.length` ? Maybe [line 236 too](https://github.com/vuetifyjs/vuetify/blob/0a562f087658c1e533a4f431b70031daa4bcde01/packages/vuetify/src/components/VFileInput/VFileInput.tsx#L236)

**Comment by mhio** [comment]
after the above fixes, the `.reset()` also triggers https://github.com/vuetifyjs/vuetify/issues/16167
