### ISSUE TITLE
[Bug Report][3.0.1] Can't override $overlay-scrim-background variable

### ISSUE THREAD

**Issue by dyc3** [vuetifyjs/vuetify#16103]
### Environment
**Vuetify Version:** 3.0.1
**Vue Version:** 3.2.45
**Browsers:** Firefox 106.0
**OS:** Ubuntu undefined

### Steps to reproduce
1. Use Vite
2. Attempt to override the sass var `$overlay-scrim-background`

### Expected Behavior
Expected no compiler errors, and for the variable to overwritten

### Actual Behavior
sass compiler error

```
[1]   File: /home/carson/Documents/code/opentogethertube/client/src/vuetify-settings.scss:2:2
[1]   Error: This variable was not declared with !default in the @used module.
[1]     ╷
[1]   2 │     $overlay-scrim-background: "#000000"
[1]     │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]     ╵
[1]     src/vuetify-settings.scss 2:2                      @use
[1]     plugin-vuetify:components/VLabel/VLabel.sass 1:1  root stylesheet
[1]       at Object.wrapException (/home/carson/Documents/code/opentogethertube/node_modules/sass/sass.dart.js:1247:17)
[1]       at _EvaluateVisitor2._async_evaluate0$_assertConfigurationIsEmpty$2$nameInError (/home/carson/Documents/code/opentogethertube/node_modules/sass/sass.dart.js:70256:15)
[1]       at _EvaluateVisitor2._async_evaluate0$_assertConfigurationIsEmpty$1 (/home/carson/Documents/code/opentogethertube/node_modules/sass/sass.dart.js:70259:19)
[1]       at /home/carson/Documents/code/opentogethertube/node_modules/sass/sass.dart.js:71433:27
...
```

### Reproduction Link
[https://stackblitz.com/edit/vitejs-vite-jkhuhh?file=src/vuetify-settings.scss](https://stackblitz.com/edit/vitejs-vite-jkhuhh?file=src/vuetify-settings.scss)

**Comment by nekosaur** [comment]
https://stackblitz.com/edit/vitejs-vite-oixaus?file=src%2Fvuetify-settings.scss,src%2Fmain.ts

This is using information from docs, specifically the section https://next.vuetifyjs.com/en/features/sass-variables/#component-specific-variables

I'll keep this issue open for a little bit because I do think we can probably improve the instructions.
