### ISSUE TITLE
[Bug Report][3.0.5] v-autocomplete throwing globalStack.at is not a function error

### ISSUE THREAD

**Issue by JeremyQtweb** [vuetifyjs/vuetify#16303]
### Environment
**Vuetify Version:** 3.0.5
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0, Microsoft Edge
**OS:** Windows 10

### Steps to reproduce
Attempt to render a v-autocomplete on app load / page reload, and it throws an error "TypeError: globalStack.at is not a function."

### Expected Behavior
Render the v-autocomplete component

### Actual Behavior
Throws an exception: "TypeError: globalStack.at is not a function"

### Reproduction Link
[https://github.com/JeremyQtweb/vuetify-global-at-error.git](https://github.com/JeremyQtweb/vuetify-global-at-error.git)

### Other comments
**Error stack**
```
500
globalStack.at is not a function

at callWithErrorHandling (C:\Projects\Research\nuxt-3-page-repro\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
at callWithAsyncErrorHandling (C:\Projects\Research\nuxt-3-page-repro\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:166:21)
at getter (C:\Projects\Research\nuxt-3-page-repro\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:1724:24)
at doWatch (C:\Projects\Research\nuxt-3-page-repro\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:1749:13)
at Module.watchEffect (C:\Projects\Research\nuxt-3-page-repro\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:1644:12)
at Module.useStack (C:\Projects\Research\nuxt-3-page-repro\node_modules\vuetify\lib\composables\stack.mjs:30:25)
at Object.setup [as _setup] (C:\Projects\Research\nuxt-3-page-repro\node_modules\vuetify\lib\components\VOverlay\VOverlay.mjs:140:32)
at setup (C:\Projects\Research\nuxt-3-page-repro\node_modules\vuetify\lib\util\defineComponent.mjs:57:37)
at callWithErrorHandling (C:\Projects\Research\nuxt-3-page-repro\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:157:22)
```

**Additional:**
- Nuxt Version: 3.0.0
- If you comment out the v-autocomplete component, reload the page, then uncomment and let HMR kick in, the component renders and is usable.
- As soon as you intentionally reload the page, or build and load from scratch, the `globalstack.at` error is thrown.
- This site was created using the Nuxt3 starter template: `npx nuxi init <app>` and uses the experimental `<suspense>` component somewhere in the Nuxt app building / loading functionality. I haven't figured out how to disable it for testing.

**Comment by KaelWD** [comment]
`node -v`

**Comment by JeremyQtweb** [comment]
Oh maan thank you @KaelWD. This is a research project for - hopefully - a 2023 upgrade to N/V/VFY3. We still have to run our main project on v14.x due to IE11 related legacy support things. I completely forgot to switch Node Version. Oh my gawd what a doofus! 

Note: Issue resolved with Node v16 and up

**Comment by JeremyQtweb** [comment]
Resolved with Node v16 and up

**Comment by huakerHK** [comment]
有解决吗？我也有这个问题

**Comment by huakerHK** [comment]
Is there a solution? I also have this problem

**Comment by chehaoxin** [comment]
Me too

**Comment by guxuerui** [comment]
> There is still this problem with Node v16 and up

Oh Yes!  I also have this problem now, and I'm using Chrome version 89 & node v18.14.2. So, how to solve this problem?
