### ISSUE TITLE
[Bug Report][3.0.6] Cannot import individual components

### ISSUE THREAD

**Issue by skamansam** [vuetifyjs/vuetify#16319]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux x86_64

### Steps to reproduce
```
pnpm create vuetify
# name it vuetify-cypress
cd vuetify-cypress
pnpm install -D cypress
```
copy the suggestion from jessica sachs at https://github.com/cypress-io/cypress/issues/17387#issuecomment-900436087
[changes were made to fit the codebase]
```
// Support File: cypress/support/commands.jsx
// import VApp from 'vuetify';  // doesn't work
// import VApp from 'vuetify/lib';   // doesn't work
// import VApp from 'vuetify/lib/components';   // doesn't work
import VApp from 'vuetify/lib/components/VApp';   // doesn't work
import vuetify from '@/plugins/vuetify';

import { mount as cypressMount } from 'cypress/vue'

Cypress.Commands.add('mount', (component, overrides = {}) => {
  const mountOptions = {
    /* Anything you'd normally do in Vue Test Utils to setup your component */
    plugins: [ vuetify, i18n ],

    ...overrides // you'll wanna break this out to make it easier to override certain plugin settings (like Vuex)
  }

  return cypressMount(() => (<VApp>
    <div>
      <component is={component}/>
    </div>
  </VApp>), mountOptions)
})

```
use the generated test from cypress:
```
import HelloWorld from './HelloWorld.vue'
describe('<HelloWorld />', () => {
  it('renders', () => {
    cy.mount(HelloWorld)
  })
})
```

run cypress with `pnpm cypress open` and navigate to the component tests

### Expected Behavior
cypress should show the tests as passed

### Actual Behavior
I get the following error rendered in the browser panel:
```
[plugin:vite:import-analysis] Failed to resolve import "vuetify/lib/components/VApp" from "cypress/support/commands.jsx". Does the file exist?
/home/sam/workspace/vuetify-cypress/cypress/support/commands.jsx:28:17
1  |  import VApp from "vuetify/lib/components/VApp";
   |                    ^
2  |  import vuetify from "@/plugins/vuetify";
3  |  import { mount as cypressMount } from "cypress/vue";
    at formatError (file:///home/sam/workspace/vuetify-cypress/node_modules/.pnpm/vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40281:46)
    at TransformContext.error (file:///home/sam/workspace/vuetify-cypress/node_modules/.pnpm/vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40277:19)
    at normalizeUrl (file:///home/sam/workspace/vuetify-cypress/node_modules/.pnpm/vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37145:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransformContext.transform (file:///home/sam/workspace/vuetify-cypress/node_modules/.pnpm/vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:37278:47)
    at async Object.transform (file:///home/sam/workspace/vuetify-cypress/node_modules/.pnpm/vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:40534:30)
    at async loadAndTransform (file:///home/sam/workspace/vuetify-cypress/node_modules/.pnpm/vite@3.2.5_sass@1.57.1/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:36921:29
```

### Reproduction Link
[https://github.com/skamansam/vuetify-cypress](https://github.com/skamansam/vuetify-cypress)

**Comment by KaelWD** [comment]
`vuetify/components/VApp`

**Comment by skamansam** [comment]
Thank you!
