### ISSUE TITLE
[Bug Report][3.0.6] VLocaleProvider doesn't work with latest vue-18n version

### ISSUE THREAD

**Issue by peshanghiwa** [vuetifyjs/vuetify#16335]
### Environment
**Vuetify Version:** 3.0.6
**Vue Version:** 3.2.45
**Browsers:** Chrome 108.0.0.0
**OS:** Linux

### Steps to reproduce
Implement normal Internationalization configurations of Vuetify with vue-i18n using the official docs:
https://next.vuetifyjs.com/en/features/internationalization/#vue-i18n

And then use VLocaleProvider Component as shown in the official docs:
https://next.vuetifyjs.com/en/features/internationalization/#rtl

### Expected Behavior
To be able to use the functionalities of the component such as RTL, Locale etc...

### Actual Behavior
I get a warning and an error breaking the vue app.

error:
```log
Uncaught SyntaxError: Need to install with `app.use` function (at message-compiler.mjs:54:19)
    at createCompileError (message-compiler.mjs:54:19)
    at createI18nError (vue-i18n.mjs:92:12)
    at Object.useI18n (vue-i18n.mjs:2234:15)
    at Object.provide (vue-i18n.ts:38:23)
    at provideLocale (locale.ts:54:23)
    at Object.setup [as _setup] (VLocaleProvider.tsx:24:28)
    at setup (defineComponent.tsx:77:37)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7246:29)
    at setupComponent (runtime-core.esm-bundler.js:7201:11)
```

warning:
```log
[Vue warn]: Unhandled error during execution of setup function 
  at <VLocaleProvider rtl="" > 
  at <App>
```

### Reproduction Link
[https://github.com/peshanghiwa/Vuetify-VLocaleProvider-with-vue-i18n-Issue-repo](https://github.com/peshanghiwa/Vuetify-VLocaleProvider-with-vue-i18n-Issue-repo)

**Comment by KaelWD** [comment]
You don't have `app.use(i18n)`
