### ISSUE TITLE
[Bug Report][3.1.14] [Vue warn]: Failed setting prop "prefix" on [component] in unit tests

### ISSUE THREAD

**Issue by Oleksii14** [vuetifyjs/vuetify#17185]
### Environment
**Vuetify Version:** 3.1.14
**Vue Version:** 3.2.47
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Clone the repo
2. `yarn install`
3. `yarn test:unit`

### Expected Behavior
No warnings are thrown when testing Vuetify components

### Actual Behavior
While writing unit tests for components that use Vuetify components, there are many warnings regarding `prefix` property. The issue reproduces not only in `VTextField`, but also in other components like `VAutoComplete`

### Reproduction Link
[https://github.com/Oleksii14/vuetify-test-utils-issue](https://github.com/Oleksii14/vuetify-test-utils-issue)

**Comment by Oleksii14** [comment]
Full warning

```
[Vue warn]: Failed setting prop "prefix" on <v-text-field-stub>: value undefined is invalid. TypeError: Cannot set property prefix of #<Element> which has only a getter
    at patchDOMProp (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:269:17)
    at patchProp (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:387:9)
    at mountElement (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5164:21)
    at processElement (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5136:13)
    at patch (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5056:21)
    at ReactiveEffect.componentUpdateFn [as fn] (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5594:21)
    at ReactiveEffect.run (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/reactivity/dist/reactivity.cjs.js:194:25)
    at instance.update (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5701:56)
    at setupRenderEffect (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5715:9)
    at mountComponent (/Users/oleksiishaposhnikov/work/vuetify-project/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5497:9) 
  at <VTextField> 
  at <HelloWorld ref="VTU_COMPONENT" > 
  at <VTUROOT>
```

**Comment by Oleksii14** [comment]
What do you mean? I use `shallowMount`, this is the reason the "stub" is used

**Comment by KaelWD** [comment]
yes

**Comment by KaelWD** [comment]
correction: any component that has a prop sharing a name with a readonly property on Element
https://developer.mozilla.org/en-US/docs/Web/API/Element/prefix

**Comment by Oleksii14** [comment]
@KaelWD could you suggest a fix for this warning for usage with `shallowMount`?
