### ISSUE TITLE
[Bug Report][2.6.0] Triggering click on action button inside of v-dialog in jest causes error

### ISSUE THREAD

**Issue by Dimas-e63s** [vuetifyjs/vuetify#17260]
### Environment
**Vuetify Version:** 2.6.0
**Vue Version:** 2.6.14
**Browsers:** Chrome 112.0.0.0
**OS:** Mac OS 10.15.7

### Steps to reproduce
1. Clone the repo
2. Run the `npm run test:unit` script

### Expected Behavior
Using `user.click` from `@testing-library/user-event` library triggers event on the `v-btn` component inside of `v-dialog`

### Actual Behavior
Console shows an error ` Error: Uncaught [TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.]` when using `user.click` on interactive element inside of `v-dialog`

### Reproduction Link
[https://github.com/Dimas-e63s/vuetify-dialog](https://github.com/Dimas-e63s/vuetify-dialog)

### Other comments
Using VTU (vue-test-utils) with `mount+trigger` [works fine](https://github.com/Dimas-e63s/vuetify-dialog/blob/master/tests/unit/vtu-example.spec.js), but when using `@testing-library/user-event` is not.

Stack trace from error:
```
at Object.exports.convert (node_modules/jsdom/lib/jsdom/living/generated/Node.js:25:9)
      at HTMLDivElement.contains (node_modules/jsdom/lib/jsdom/living/generated/Node.js:253:28)
      at VueComponent.onFocusin (node_modules/vuetify/dist/webpack:/Vuetify/src/components/VDialog/VDialog.ts:229:28)
      at callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at EventTargetImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at Object.exports.fireFocusEventWithTargetAdjustment (node_modules/jsdom/lib/jsdom/living/helpers/focusing.js:103:10)
      at HTMLButtonElementImpl.blur (node_modules/jsdom/lib/jsdom/living/nodes/HTMLOrSVGElement-impl.js:81:14)
      at HTMLButtonElement.blur (node_modules/jsdom/lib/jsdom/living/generated/HTMLElement.js:128:34)
      at VueComponent.click (node_modules/vuetify/dist/webpack:/Vuetify/src/components/VBtn/VBtn.ts:162:69)
      at invokeWithErrorHandling (node_modules/vue/dist/vue.runtime.common.dev.js:2919:30)
      at HTMLButtonElement.invoker (node_modules/vue/dist/vue.runtime.common.dev.js:1732:20)
      at HTMLButtonElement.original._wrapper (node_modules/vue/dist/vue.runtime.common.dev.js:7393:33)
      at HTMLButtonElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLButtonElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLButtonElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLButtonElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:47:43
      at Object.eventWrapper (node_modules/@testing-library/dom/dist/config.js:25:23)
      at Object.wrapEvent (node_modules/@testing-library/user-event/dist/cjs/event/wrapEvent.js:8:28)
      at Object.dispatchEvent (node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:47:22)
      at Object.dispatchUIEvent (node_modules/@testing-library/user-event/dist/cjs/event/dispatchEvent.js:24:26)
      at Mouse.up (node_modules/@testing-library/user-event/dist/cjs/system/pointer/mouse.js:91:30)
      at PointerHost.release (node_modules/@testing-library/user-event/dist/cjs/system/pointer/index.js:74:28)
      at pointerAction (node_modules/@testing-library/user-event/dist/cjs/pointer/index.js:62:47)
      at Object.pointer (node_modules/@testing-library/user-event/dist/cjs/pointer/index.js:35:9)
      at Object.<anonymous> (tests/unit/vtl-example.spec.js:26:5)
```

**Comment by KaelWD** [comment]
Add `console.log(target)` to line 15071 of vuetify/dist/vuetify.js and it's a HTMLButtonElement, this seems like a bug with your testing library rather than vuetify.
