### ISSUE TITLE
Module build failed: TypeError when calling "npm run dev"

### ISSUE THREAD

**Issue by desile** [vuetifyjs/vuetify#1972]
Hello!
You are making awesome framework and I really want to start using it, but I faced with little problem. Maybe it is due to incorrect versions in the environment.

I have:
- vue-cli 2.8.1
- npm 3.5.2
- node 4.2.6
Then I type "vue init vuetifyjs/webpack" , "npm install", "npm run dev". And it give me the error when _localhost:8080_ starts loading.

Error:
```
ERROR in ./~/css-loader!./~/stylus-loader!./src/stylus/main.styl
Module build failed: TypeError: Path must be a string. Received [Function: includes]
    at assertPath (path.js:8:11)
    at Object.posix.normalize (path.js:450:3)
    at normalizePaths (/home/desile/magister/front/node_modules/stylus-loader/lib/pathcache.js:301:21)
    at stylusFile (/home/desile/magister/front/node_modules/stylus-loader/lib/pathcache.js:102:14)
    at /home/desile/magister/front/node_modules/stylus-loader/lib/pathcache.js:159:32
    at tryCatchResolve (/home/desile/magister/front/node_modules/when/lib/apply.js:46:23)
    at callAndResolve (/home/desile/magister/front/node_modules/when/lib/apply.js:30:12)
    at callAndResolveNext (/home/desile/magister/front/node_modules/when/lib/apply.js:40:4)
    at tryCatchReject3 (/home/desile/magister/front/node_modules/when/lib/makePromise.js:851:7)
    at runContinuation3 (/home/desile/magister/front/node_modules/when/lib/makePromise.js:809:4)
 @ ./src/stylus/main.styl 4:14-119 13:2-17:4 14:20-125
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8081 webpack/hot/dev-server ./src/main.js


```

Thank you!

**Comment by KaelWD** [comment]
The issue list of this repo is <strong>exclusively</strong> for bug reports and feature requests. For general questions, please join <a href="https://chat.vuetifyjs.com">the Discord chat room</a>.

It's probably got something to do with your ancient version of node.

**Comment by desile** [comment]
Yes, I update node to version 6.11.1 and now framework works!
