### ISSUE TITLE
[Bug Report][3.6.10] VTreeview - "open is not defined" when using Nuxt

### ISSUE THREAD

**Issue by craigrileyuk** [vuetifyjs/vuetify#20071]
### Environment
**Vuetify Version:** 3.6.10
**Vue Version:** 3.4.31
**Browsers:** Firefox 127.0
**OS:** Mac OS 10.15

### Steps to reproduce
https://github.com/vuetifyjs/vuetify/blob/27b4b1e52060b6bee13a290a4829f935f1bd9c05/packages/vuetify/src/labs/VTreeview/VTreeview.tsx#L169-L171

This only seems to be an issue when using Nuxt to render the component. On the line cited above, the component returns an object named "open" from the setup function. This is not defined anywhere else in the file and throws an error.

### Expected Behavior
Treeview to function with Nuxt

### Actual Behavior
500

open is not defined

at setup (./node_modules/.pnpm/vuetify@3.6.10_typescript@5.5.2_vite-plugin-vuetify@2.0.3_vue@3.4.31_typescript@5.5.2_/node_modules/vuetify/lib/util/defineComponent.mjs:37:37)
at callWithErrorHandling (./node_modules/.pnpm/@vue+runtime-core@3.4.31/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:196:19)
at setupStatefulComponent (./node_modules/.pnpm/@vue+runtime-core@3.4.31/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7577:25)
at setupComponent (./node_modules/.pnpm/@vue+runtime-core@3.4.31/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7538:36)
at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.4.31_vue@3.4.31_typescript@5.5.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:619:15)
at renderVNode (./node_modules/.pnpm/@vue+server-renderer@3.4.31_vue@3.4.31_typescript@5.5.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:753:14)
at renderVNodeChildren (./node_modules/.pnpm/@vue+server-renderer@3.4.31_vue@3.4.31_typescript@5.5.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:769:5)
at renderElementVNode (./node_modules/.pnpm/@vue+server-renderer@3.4.31_vue@3.4.31_typescript@5.5.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:816:9)
at renderVNode (./node_modules/.pnpm/@vue+server-renderer@3.4.31_vue@3.4.31_typescript@5.5.2_/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:751:9)

### Reproduction Link
[https://play.vuetifyjs.com/#...](https://play.vuetifyjs.com/#eNqNUk2L2zAQ/StCl2Qhtrps6cEkZUtPhR56KL3EOWjtCdGiL6Sx0yXkv3dky42T7GHB2NJ7T/NmnrU98Rga8c37su+AV3yNYLyWCF9ry9i6L6T3w3LYNM6iVBZChgj88zsA9AqOE8JYXxjXgq6cBwvtpubjouYXSaXIJxKFdPpHWs/ZRBaoUAMprDRwR/ZSd4n0Eg9zsgUbFb4R0zjjZYNXptrJtmgOSrcBbOrL/iTkewYuUjFNLG5HTsiYyFrMkqJtbILyyCJgNwamjHcB2YkF2LMz2wdn2IJCXiQ5Y1Q3IhuTYZskWm53DxfmfzATObZ0mnpMsVRsEZ2BvdJQ4l9crCYyxUKkOBArughBvK+bsqjYdpfB8/BNncy6vMqJGkr/gG1yShaO7BdNpyIslwGi0z2sqOdXaPCBVJeeMzkNSmb0XYsxOqrGV3xMrTDSl6/RWbqRw+k6E3RNqqlezSnNtK/5AdHHSoimtXSM7p7qQ2kBhfVGPJNMhM6iMlC0zjw/lZ/Lp0fRqohzvIRoipfgjpQXVal5TmTwQbV/+4BXVpLFl/Lx02iRsULLl5g87moLMuwhFJRtCwHCR2e6OXY11w13N1uyP9eWHn5e2U7r4bX7B8unVPg=)

**Comment by KaelWD** [comment]
Fixed by #20192
