### ISSUE TITLE
[Bug Report] A La Carte doesn't build in vue-pwa template projects (expected "indent", got "!")

### ISSUE THREAD

**Issue by flybayer** [vuetifyjs/vuetify#2537]
### Versions and Environment
**Vuetify:** 0.17.1
**Vue:** 2.5.4
**Browsers:** Firefox 58.0
**OS:** Mac OS 10.13

### Steps to reproduce
Both development and production builds are broken

### Expected Behavior
A La Carte to build and work like it does with the vuetifyjs/a-la-carte template

### Actual Behavior
Build is broken with this error for each imported component:
```
ERROR in ./node_modules/css-loader!./node_modules/stylus-loader!./node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?{"minimize":true,"sourceMap":true}!./node_modules/stylus-loader?{"sourceMap":true}!./node_modules/vuetify/src/stylus/app.styl
Module build failed: ParseError: /private/var/tmp/alc-pwa/node_modules/vuetify/src/stylus/app.styl:4:94
   1| // style-loader: Adds some css to the DOM by adding a <style> tag
   2|
   3| // load the styles
   4| var content = require("!!../../../css-loader/index.js?{\"minimize\":true,\"sourceMap\":true}!../../../stylus-loader/index.js?{\"sourceMap\":true}!./app.styl");
---------------------------------------------------------------------------------------------------^
   5| if(typeof content === 'string') content = [[module.id, content, '']];
   6| if(content.locals) module.exports = content.locals;
   7| // add the styles to the DOM

expected "indent", got "!"

    at Parser.error (/private/var/tmp/alc-pwa/node_modules/stylus/lib/parser.js:259:11)
    at Parser.expect (/private/var/tmp/alc-pwa/node_modules/stylus/lib/parser.js:287:12)
    at Parser.block (/private/var/tmp/alc-pwa/node_modules/stylus/lib/parser.js:845:12)
    at Parser.selector (/private/var/tmp/alc-pwa/node_modules/stylus/lib/parser.js:1555:24)
    at Parser.ident (/private/var/tmp/alc-pwa/node_modules/stylus/lib/parser.js:1446:25)
    at Parser.stmt (/private/var/tmp/alc-pwa/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (/private/var/tmp/alc-pwa/node_modules/stylus/lib/parser.js:685:21)
    at Parser.parse (/private/var/tmp/alc-pwa/node_modules/stylus/lib/parser.js:236:25)
    at Renderer.render (/private/var/tmp/alc-pwa/node_modules/stylus/lib/renderer.js:80:22)
    at /private/var/tmp/alc-pwa/node_modules/stylus-loader/index.js:165:12
    at tryCatchReject (/private/var/tmp/alc-pwa/node_modules/when/lib/makePromise.js:840:30)
    at runContinuation1 (/private/var/tmp/alc-pwa/node_modules/when/lib/makePromise.js:799:4)
    at Fulfilled.when (/private/var/tmp/alc-pwa/node_modules/when/lib/makePromise.js:590:4)
    at Pending.run (/private/var/tmp/alc-pwa/node_modules/when/lib/makePromise.js:481:13)
    at Scheduler._drain (/private/var/tmp/alc-pwa/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/private/var/tmp/alc-pwa/node_modules/when/lib/Scheduler.js:27:9)
 @ ./node_modules/vuetify/src/stylus/app.styl 4:14-279
 @ ./src/main.js
```

### Reproduction Link
[https://github.com/flybayer/vuetify-a-al-carte-bug](https://github.com/flybayer/vuetify-a-al-carte-bug)

**Comment by nekosaur** [comment]
Remove the `.styl` rule section from `webpack.base.conf.js`

**Comment by flybayer** [comment]
@nekosaur hey, I can't remove `.styl` because I need it for other things in my app.

**Comment by KaelWD** [comment]
The stylus loader config is generated by `utils.js`: https://github.com/flybayer/vuetify-a-al-carte-bug/blob/aa150743e1b9eb665c2ad8ef0730324edf504705/build/webpack.dev.conf.js#L19-L21

**Comment by flybayer** [comment]
Oh! Yes, thank you @KaelWD! Issue resolved by removing the `.style` rule from webpack base config.
