### ISSUE TITLE
Error not compiling

### ISSUE THREAD

**Issue by JENDXOR** [vuetifyjs/vuetify#2578]
Please can anyone help me on these issue. I'm using vuetify.js 0.17.1 but still getting errors on some component

JIDEX@JENDXOR MINGW64 ~/Desktop
$ cd C:\\Users\\JIDEX\\Documents\\vueprojects\\ndaapproject\\test\\cabsoldarui

JIDEX@JENDXOR MINGW64 ~/Documents/vueprojects/ndaapproject/test/cabsoldarui
$ npm run dev

> cabsoldarui@1.0.0 dev C:\Users\JIDEX\Documents\vueprojects\ndaapproject\test\cabsoldarui
> node build/dev-server.js

module.js:529
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\JIDEX\Documents\vueprojects\ndaapproject\test\cabsoldarui\build\utils.js:3:25)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cabsoldarui@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cabsoldarui@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JIDEX\AppData\Roaming\npm-cache\_logs\2017-11-20T17_24_13_747Z-debug.log

JIDEX@JENDXOR MINGW64 ~/Documents/vueprojects/ndaapproject/test/cabsoldarui
$ npm install --save
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 119 packages in 87.868s

JIDEX@JENDXOR MINGW64 ~/Documents/vueprojects/ndaapproject/test/cabsoldarui
$ npm run dev

> cabsoldarui@1.0.0 dev C:\Users\JIDEX\Documents\vueprojects\ndaapproject\test\cabsoldarui
> node build/dev-server.js

> Starting dev server...

 ERROR  Failed to compile with 3 errors                                              18:26:54

These dependencies were not found:

* vuetify/es5/components/VTabsContent in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/Settings/Settings.vue
* vuetify/es5/components/VTabsItems in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/Settings/Settings.vue
* vuetify/es5/components/VCardTitle in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/Settings/Settings.vue

To install them, you can run: npm install --save vuetify/es5/components/VTabsContent vuetify/es5/components/VTabsItems vuetify/es5/components/VCardTitle
> Listening at http://localhost:8080

**Comment by Mathem8tic** [comment]
What do you have in your package.json?

**Comment by johnleider** [comment]
Please only create issues with the provided [issue creator](https://issues.vuetifyjs.com). In the boilerplate for creating an issue, it explains that any ticket made without this will be automatically closed. Thank you.
