### ISSUE TITLE
Syntax Error while compiling Stylus with Nuxt.JS

### ISSUE THREAD

**Issue by hydroid7** [vuetifyjs/vuetify#5215]
### Versions and Environment
Vuetify: 1.2.6
Vue: Nuxt 2.1.0
Browsers: all
OS: Linux

### Steps to reproduce

Clone the example repository and run `yarn && yarn dev`
### Expected Behavior

No error.
### Actual Behavior

Syntax error while compiling Stylus.
### Reproduction Link

https://github.com/hydroid7/nuxt-vuetify-syntax-error

### Comments
Related to https://github.com/nuxt/nuxt.js/issues/3611

**Comment by KaelWD** [comment]
Can you paste the error here?

**Comment by hydroid7** [comment]
The error is:

```
✖ error /nuxt-vuetify-syntax-error/node_modules/vuetify/src/stylus/components/_app.styl:1
  (function (exports, require, module, __filename, __dirname) { @import '../bootstrap'
  ^
  
  SyntaxError: Invalid or unexpected token
  at createScript (vm.js:80:10)
  at Object.runInThisContext (vm.js:139:10)
  at Module._compile (module.js:616:28)
  at Object.Module._extensions..js (module.js:663:10)
  at Module.load (module.js:565:32)
  at tryModuleLoad (module.js:505:12)
  at Function.Module._load (module.js:497:3)
  at Module.require (module.js:596:17)
  at require (internal/module.js:11:18)
  at Object.<anonymous> (/nuxt-vuetify-syntax-error/node_modules/vuetify/es5/components/VApp/VApp.js:13:1)
  at Module._compile (module.js:652:30)
  at Object.Module._extensions..js (module.js:663:10)
  at Module.load (module.js:565:32)
  at tryModuleLoad (module.js:505:12)
  at Function.Module._load (module.js:497:3)
  at Module.require (module.js:596:17)
```

**Comment by KaelWD** [comment]
https://github.com/nuxt/nuxt.js/issues/3932#issuecomment-423571580

The vuetifyjs/nuxt template was updated to nuxt 2.0 by @Codefa, apparently without testing. This has since been fixed: https://github.com/vuetifyjs/nuxt/pull/60
