### ISSUE TITLE
[Bug Report] Testing Vuetify with Jest Fails

### ISSUE THREAD

**Issue by geekox86** [vuetifyjs/vuetify#7086]
### Versions and Environment
**Vuetify:** 1.5.13
**Vue:** 2.6.10
**Browsers:** Chrome 74.0.3729.108
**OS:** Mac OS 10.14.4

### Steps to reproduce
Run `yarn test` and filter `tests/index.ts` to be executed.

### Expected Behavior
Test should not complain about importing Vuetify.

### Actual Behavior
```
TypeError: Cannot read property 'extend' of undefined

      1 | import VueApolloGraphQLPlugin from '@/codes/index'
      2 | import Vue from 'vue'
    > 3 | import Vuetify from 'vuetify'
        | ^
      4 | 
      5 | Vue.use(Vuetify)
      6 | 

      at Module.srcMixinsThemeableTs (node_modules/vuetify/dist/webpack:/Vuetify/src/mixins/themeable.ts:21:19)
      at __webpack_require__ (node_modules/vuetify/dist/webpack:/Vuetify/webpack/bootstrap:19:1)
      at Module.srcComponentsVAppVAppJs (node_modules/vuetify/dist/vuetify.js:593:62)
      at __webpack_require__ (node_modules/vuetify/dist/webpack:/Vuetify/webpack/bootstrap:19:1)
      at Module.srcComponentsVAppIndexJs (node_modules/vuetify/dist/webpack:/Vuetify/src/components/VApp/index.js:1:1)
      at __webpack_require__ (node_modules/vuetify/dist/webpack:/Vuetify/webpack/bootstrap:19:1)
      at Module.srcComponentsIndexTs (node_modules/vuetify/dist/webpack:/Vuetify/src/components/index.ts:1:1)
      at __webpack_require__ (node_modules/vuetify/dist/webpack:/Vuetify/webpack/bootstrap:19:1)
      at Module.srcIndexTs (node_modules/vuetify/dist/vuetify.js:29791:56)
      at __webpack_require__ (node_modules/vuetify/dist/webpack:/Vuetify/webpack/bootstrap:19:1)
      at node_modules/vuetify/dist/webpack:/Vuetify/webpack/bootstrap:83:1
      at node_modules/vuetify/dist/vuetify.js:372:6
      at webpackUniversalModuleDefinition (node_modules/vuetify/dist/webpack:/Vuetify/webpack/universalModuleDefinition:3:1)
      at Object.<anonymous> (node_modules/vuetify/dist/webpack:/Vuetify/webpack/universalModuleDefinition:1:1)
      at Object.<anonymous> (tests/index.ts:3:1)
```

### Reproduction Link
<a href="https://github.com/geekox86/vue-apollo-graphql" target="_blank">https://github.com/geekox86/vue-apollo-graphql</a>

**Comment by KaelWD** [comment]
You're mocking vue
