### ISSUE TITLE
error while upgrading from vuetify 1.5

### ISSUE THREAD

**Issue by afnan** [vuetifyjs/vuetify#7995]
Could not create it on the given issue creator because I do not have url for codepen etc
Trying to upgrade to new version on a laravel installation. It works fine witn 1.5 module. 

1. $ npm uninstall node-sass
2. $ npm i -D sass
3. $ npm uninstall -S vuetify
4. $ npm install vuetify --save
5. npm run watch

 ```
ERROR  Failed to compile with 2 errors                                                                                                                                                              14:24:45
 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
NoSuchMethodError: method not found: 'pathToFileURL' (url.pathToFileURL is not a function)
    at runLoaders (D:\wamp64\www\RMS\node_modules\webpack\lib\NormalModule.js:302:20)
    at D:\wamp64\www\RMS\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\wamp64\www\RMS\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\wamp64\www\RMS\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at render (D:\wamp64\www\RMS\node_modules\sass-loader\lib\loader.js:52:13)
    at Function.call$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:53423:16)
    at _render_closure1.call$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:33244:12)
    at _RootZone.runBinary$3$3 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:19644:18)
    at _RootZone.runBinary$3 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:19648:19)
    at _FutureListener.handleError$1 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18116:19)
    at _Future__propagateToListeners_handleError.call$0 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18401:40)
    at Object._Future__propagateToListeners (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:3460:88)
    at _Future._completeError$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18237:9)
    at _SyncCompleter._completeError$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18103:19)
    at _SyncCompleter.completeError$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18072:12)
    at _AsyncAwaitCompleter_completeError_closure.call$0 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:17623:29)
    at Object._microtaskLoop (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:3510:21)
    at StaticClosure._startMicrotaskLoop (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:3516:11)
    at _AsyncRun__scheduleImmediateJsOverride_internalCallback.call$0 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:17530:21)
    at invokeClosure (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:1343:26)
    at Immediate._onImmediate (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:1364:18)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

 error  in ./resources/sass/app.scss

Module build failed (from ./node_modules/sass-loader/lib/loader.js):
NoSuchMethodError: method not found: 'pathToFileURL' (url.pathToFileURL is not a function)

 @ ./resources/sass/app.scss 2:14-255
                                                                                                                                                                              Asset      Size   Chunks
      Chunk Names
/js/app.js  3.03 MiB  /js/app  [emitted]  /js/app

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
NoSuchMethodError: method not found: 'pathToFileURL' (url.pathToFileURL is not a function)
    at runLoaders (D:\wamp64\www\RMS\node_modules\webpack\lib\NormalModule.js:302:20)
    at D:\wamp64\www\RMS\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\wamp64\www\RMS\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\wamp64\www\RMS\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at render (D:\wamp64\www\RMS\node_modules\sass-loader\lib\loader.js:52:13)
    at Function.call$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:53423:16)
    at _render_closure1.call$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:33244:12)
    at _RootZone.runBinary$3$3 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:19644:18)
    at _RootZone.runBinary$3 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:19648:19)
    at _FutureListener.handleError$1 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18116:19)
    at _Future__propagateToListeners_handleError.call$0 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18401:40)
    at Object._Future__propagateToListeners (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:3460:88)
    at _Future._completeError$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18237:9)
    at _SyncCompleter._completeError$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18103:19)
    at _SyncCompleter.completeError$2 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:18072:12)
    at _AsyncAwaitCompleter_completeError_closure.call$0 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:17623:29)
    at Object._microtaskLoop (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:3510:21)
    at StaticClosure._startMicrotaskLoop (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:3516:11)
    at _AsyncRun__scheduleImmediateJsOverride_internalCallback.call$0 (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:17530:21)
    at invokeClosure (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:1343:26)
    at Immediate._onImmediate (D:\wamp64\www\RMS\node_modules\sass\sass.dart.js:1364:18)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
 @ ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/sass/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
NoSuchMethodError: method not found: 'pathToFileURL' (url.pathToFileURL is not a function)
 @ ./resources/sass/app.scss 2:14-255
```

**Comment by wrtisans** [comment]
i've the same error.. somee idea how to fix it?

**Comment by ernarkazakh** [comment]
Same here :(

**Comment by DRoet** [comment]
might be related to the newest version of sass... which node version are you using?
https://github.com/sass/dart-sass/releases/tag/1.22.8

**Comment by ernarkazakh** [comment]
> might be related to the newest version of sass... which node version are you using?
> https://github.com/sass/dart-sass/releases/tag/1.22.8

v12.7.0

**Comment by DRoet** [comment]
and which version of `sass`? maybe try rolling back to `1.22.7`

**Comment by ernarkazakh** [comment]
> and which version of `sass`? maybe try rolling back to `1.22.7`

Running `npm install saas@1.22` says that there is no said version

**Comment by DRoet** [comment]
are you using `@import` statements somewhere in your sass/scss file? I can't seem to reproduce this

**Comment by ernarkazakh** [comment]
> are you using `@import` statements somewhere in your sass/scss file? I can't seem to reproduce this

Im not even using saas nor scss

**Comment by DRoet** [comment]
I'd need to see a repro, I can't guess what is going wrong

**Comment by mobyface** [comment]
We also have this very same problem when upgrading to sass 1.22.8. Maybe has something todo with url('data:....') syntax inside app.scss

**Comment by kommaJules** [comment]
I have the same issue. But i don't use vuetify at all. So i don't think it is a problem in app.scss which i now assume to be part of vuetify.

I tried a couple of things and found a workaround that may work for you all. It tried downgrading like this: npm install sass@1.22.7 --save-dev

And that works! There is something wrong with the latest release at the moment. e.g. the one you get with npm install sass@1.22.8 --save-dev

**Comment by ngocnkd-1407** [comment]
Seem like have some problem with newest version of sass@1.22.8 :( It's not vuetify problem.

**Comment by DRoet** [comment]
Ok found it, either roll back to `sass` `1.22.7` OR make sure you are using node `>= 10.12.0`,
see https://github.com/sass/dart-sass/issues/780#issuecomment-514935273

**Comment by ernarkazakh** [comment]
Wow you guys are insane. Love you all

**Comment by jokova91** [comment]
Thanks, guys!  Save my day!!!

**Comment by afnan** [comment]
Update Node version. i was using 8 and installed 12 and worked fine

**Comment by shivi2191** [comment]
You all are awesome.. I only wish I could come across this discussion 4 hours earlier :)
