### ISSUE TITLE
[Bug Report] Can't compile after using yarn/npm link 

### ISSUE THREAD

**Issue by peteruithoven** [vuetifyjs/vuetify#9319]
### Environment
**Vuetify Version:** 2.1.3 
**Vue Version:** 2.6.10
**Browsers:** Firefox 69.0
**OS:** Ubuntu undefined

### Steps to reproduce
```
git clone git@github.com:vuetifyjs/vuetify.git
cd vuetify
yarn
yarn build
cd packages/vuetify
yarn link
cd ../../../
vue create vuetify-link-test
cd vuetify-link-test
vue add vuetify # choosing Default
yarn link vuetify
yarn serve
```

### Expected Behavior
Yarn serve succeeds and local vuetify is used. 

### Actual Behavior
Failed to compile:
```
yarn run v1.16.0
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 8 errors                                                                     11:17:00 PM

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load plugin jest: Cannot find module 'eslint-plugin-jest'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Plugins.load (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/config-file.js:529:35)
    at Object.load (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:342:29)
    at processText (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint-loader/index.js:278:17)
    at transform (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint-loader/index.js:252:18)
    at /home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/loader-fs-cache/index.js:127:18
```

### Reproduction Link
<a href="https://github.com/peteruithoven/vuetify-link-test" target="_blank">https://github.com/peteruithoven/vuetify-link-test</a>

### Other comments
I apologize for not providing a useful reproduction link, but I can't replicate linking on online platforms and can't commit it to a git repo. 

Both link steps reported being successful.

**Comment by peteruithoven** [comment]
I've tried installing `eslint-plugin-jest` in vuetify-link-test but after relinking to vuetify that results in the following error:
```
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load plugin eslint-plugin-local-rules: Cannot find module 'eslint-plugin-local-rules'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at Plugins.load (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/config-file.js:529:35)
    at Object.load (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:299:21)
    at Config.getConfig (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:342:29)
    at processText (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/cli-engine.js:181:33)
    at CLIEngine.executeOnText (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/cli-engine.js:690:40)
    at lint (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint-loader/index.js:278:17)
    at transform (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint-loader/index.js:252:18)
    at /home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/loader-fs-cache/index.js:127:18
```

I then installed `eslint-plugin-local-rules` (and relinked to vuetify) after which it gives this error:
```
 error  in ../vuetify/packages/vuetify/lib/index.js

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: eslint-plugin-local-rules: Cannot find "eslint-local-rules.js" (looking up from "/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint-plugin-local-rules").
    at Object.<anonymous> (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint-plugin-local-rules/index.js:9:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Plugins.load (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/plugins.js:99:26)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/config-file.js:529:35)
    at Object.load (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config/config-file.js:587:20)
    at Config.getLocalConfigHierarchy (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (/home/peteruithoven/Projects/www/vue/vuetify-link-test/node_modules/eslint/lib/config.js:299:21)

 @ ./src/plugins/vuetify.js 2:0-34 3:8-15 4:19-26
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.7.1.3:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
It actually gives this same error with a couple of files, probably for all the components that are used in the project.
```
 error  in ../vuetify/packages/vuetify/lib/components/VApp/index.js
 error  in ../vuetify/packages/vuetify/lib/components/VContent/index.js
 error  in ../vuetify/packages/vuetify/lib/components/VBtn/index.js
 error  in ../vuetify/packages/vuetify/lib/components/VToolbar/index.js
 error  in ../vuetify/packages/vuetify/lib/components/VAppBar/index.js
 error  in ../vuetify/packages/vuetify/lib/components/VGrid/index.js
 error  in ../vuetify/packages/vuetify/lib/components/VImg/index.js
```

**Comment by KaelWD** [comment]
You need to set webpack's `resolve.symlinks` to false and possibly blacklist node_modules in your .eslintignore file.

**Comment by DRoet** [comment]
@KaelWD should be noted that it only works if the project is not using a-la-carte
