### ISSUE TITLE
_this.$scopedSlots.items is not a function on v-data-table

### ISSUE THREAD

**Issue by aindong** [vuetifyjs/vuetify#976]
hello, I'm following the guide here [Data table](https://vuetifyjs.com/components/data-tables)
and I'm getting a 

> _this.$scopedSlots.items

I generated my project using vue-cli with vuetify + nuxt as the main template. here's my markup

```
      <v-layout content wrap>
            <v-flex xs12 sm12 md12>
                <v-data-table
                    v-bind:headers="headers"
                    :items="references"
                    hide-actions
                    class="elevation-1"
                >
                    
                    <template slot="items" scope="props">
                        <tr>
                            <td>{{ props.item.template_name }}</td>
                            <td>{{ props.item.reference_type }}</td>
                            <td>{{ props.item.template_link }}</td>
                            <td>{{ props.item.reference_link }}</td>
                        </tr>
                    </template>
                </v-data-table>
            </v-flex>
        </v-layout>
```

Here's the full stacktrace

```
TypeError: _this.$scopedSlots.items is not a function
    at /Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/vuetify/dist/vuetify.js:7613:40
    at Array.map (native)
    at VueComponent.genTBody (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/vuetify/dist/vuetify.js:7597:39)
    at Proxy.boundFn (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue/dist/vue.runtime.common.js:127:12)
    at Proxy.render (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/vuetify/dist/vuetify.js:7495:52)
    at VueComponent.Vue._render (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue/dist/vue.runtime.common.js:3605:22)
    at renderComponent (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6698:25)
    at RenderContext.renderNode (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6681:7)
    at RenderContext.next (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:169:14)
    at cachedWrite (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:30:9)
    at renderElement (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6741:5)
    at RenderContext.renderNode (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6685:7)
    at RenderContext.next (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:169:14)
    at cachedWrite (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:30:9)
    at renderElement (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6741:5)
    at RenderContext.renderNode (/Users/alleoindong/Public/projects/cloudwalk/aims/front/node_modules/nuxt/node_modules/vue-server-renderer/build.js:6685:7)
```

**Comment by dohomi** [comment]
@aindong did you try your code in a codepen?

**Comment by aindong** [comment]
@dohomi sorry I don't know how to try a generated https://github.com/vuetifyjs/nuxt into codepen,

but I've tried it on codepen w/o nuxt and it is working fine there.

**Comment by aindong** [comment]
I'm not sure what happened, but it's now working.... maybe something is wrong with my setup

**Comment by dohomi** [comment]
sometimes coding is like this :)

**Comment by ianfiske** [comment]
Just for posterity, I came across this error fixed it by updating vue-template-compiler.  It seems that I had updated vuetify and vuejs, but vue-template-compiler remained out-of-sync with these packages until I manually updated it.
